In [1]:
# Ejercicio 1: Clasificación de edad

# Enunciado:
# Determinar si una persona es niño, adolescente, adulto o adulto mayor según su edad.

# Código:

def clasificar_edad(edad):
    if edad < 13:
        return "Niño"
    elif edad <= 17:
        return "Adolescente"
    elif edad <= 59:
        return "Adulto"
    else:
        return "Adulto mayor"

edad = 21
categoria = clasificar_edad(edad)

print(f"Edad: {edad} años")
print(f"Categoría: {categoria}")

# Resultado:
# Edad: 21 años
# Categoría: Adulto

# Explicación breve:
# Se utiliza una función con condiciones if, elif y else
# para clasificar la edad según el rango correspondiente.

Edad: 21 años
Categoría: Adulto

In [2]:
# Ejercicio 2: Conversor de temperatura (hecho por Andrea Zelaya)

# Enunciado:
# Convertir una temperatura de grados Celsius a Fahrenheit.

# Código:

def convertir_temperatura(celsius):
    fahrenheit = (celsius * 9/5) + 32
    return fahrenheit

celsius = 30.45
fahrenheit = convertir_temperatura(celsius)

print(f"Temperatura en Celsius: {celsius}°C")
print(f"Temperatura en Fahrenheit: {fahrenheit}°F")

# Resultado:
# Temperatura en Celsius: 30°C
# Temperatura en Fahrenheit: 86.0°F

# Explicación breve:
# Se aplica la fórmula de conversión de Celsius a Fahrenheit
# utilizando una función para retornar el resultado.

Temperatura en Celsius: 30.45°C
Temperatura en Fahrenheit: 86.81°F

In [3]:

# Ejercicio 3: Calculadora básica (hecho por Andrea Zelaya)

# Enunciado:
# Realizar operaciones matemáticas básicas y validar división entre cero.

# Código:

def calculadora(num1, num2, operacion):
    if operacion == "suma":
        return num1 + num2
    elif operacion == "resta":
        return num1 - num2
    elif operacion == "multiplicacion":
        return num1 * num2
    elif operacion == "division":
        if num2 != 0:
            return num1 / num2
        else:
            return "Error: No se puede dividir entre cero"
    else:
        return "Operación no válida"

num1 = 10
num2 = 2
operacion = "division"

resultado = calculadora(num1, num2, operacion)

print(f"Resultado: {resultado}")

# Resultado:
# Resultado: 2.0

# Explicación breve:
# El programa utiliza condiciones para identificar la operación
# matemática seleccionada y validar que no exista división entre cero.

Resultado: 5.0

In [4]:
# Ejercicio 4 (Hecho por Brayan Martínez)
# Enunciado: Determinar que un número es par o impar.
# Lógica: se usa el operador (%) para recibir el residuo de la división entre 2, si el resultado es 0 es par, si no es impar.
def es_par_o_impar(numero):
    if numero % 2 == 0:
        return "El número es par."
    else:
        return "El número es impar."
    
# Datos cargador
numero = 21
print(f"el numero ingresado es: {numero}")
print(es_par_o_impar(numero))

el numero ingresado es: 21
El número es impar.

In [5]:
#Ejercicio 5 (Hecho por Brayan Martínez)
#Enunciado: tabla de multiplicar del 12.
#Lógica: se define una funcion que recibe un número, este numero llega a un for que va desde el 1 hasta el 12 para multiplicar el numero dado por cada iteración del for, luego se imprime el resultado de cada multiplicación.
def tabla_de_multiplicar(numero):
    resultado = 0
    for i in range(1,13):
        resultado = numero * i
        print(f"{numero} x {i} = {resultado}")

#cargar datos para el usuario

numero = 5
print(f"Tabla de multiplicar del {numero}:")
tabla_de_multiplicar(numero)

Tabla de multiplicar del 5:
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50
5 x 11 = 55
5 x 12 = 60

In [6]:
#Ejercicio 6 (Hecho por Brayan Martínez)
#enunciado: Contador de vocales en una frase.
#Lógica: se define una función que recibe una frase, luego se inicializa un contador en 0, se recorre cada letra de la frase y se verifica si es una vocal (a, e, i, o, u) y si lo es se incrementa el contador. Al final se devuelve el total de vocales encontradas.

def contador_de_vocales(frase):
    contador = 0
    vocales = ['a', 'e', 'i', 'o', 'u']
    for letra in frase:
        if letra.lower() in vocales:
            contador += 1
            
    return contador
        
#cargar datos para el usuario

frase = "Hola mundo"
print(f"La frase ingresada es: '{frase}'")
total_vocales = contador_de_vocales(frase)
print(f"El total de vocales en la frase es: {total_vocales}")

La frase ingresada es: 'Hola mundo'
El total de vocales en la frase es: 4

In [7]:
# Ejercicio numero 7 (hecho por Salvador Romero)
#• Defina o solicite 5 calificaciones. 
#• Calcule la suma total. 
#• Calcule el promedio. 
#• Indique si el estudiante aprobó o reprobó. 
#• Considere aprobado si el promedio es mayor o igual a 70. 

Notas = [88,89.5,78,65.8,70]
SumaTotal = sum(Notas)

promedio = sum(Notas)/len(Notas)

estado= "Aprobado" if promedio >= 70 else "Reprobado"

print(f"\n Resultados:")
print(f"Suma total: {SumaTotal:.2f}")
print(f"Promedio: {promedio:.2f}")
print(f"Estado: {estado}")

 Resultados:
Suma total: 391.30
Promedio: 78.26
Estado: Aprobado

In [8]:
#Ejercicio numero 8 (hecho por Salvador Romero)
#• Defina o solicite 10 números. 
#• Cuente cuántos son positivos, negativos y ceros. 
#• Muestre un resumen final.
Numeros = [0.23, -8, 6, 4, 45, -9, 0, 56, -1]
positivos = negativos = ceros = 0 

for i in range(len(Numeros)):
    if Numeros[i] > 0:
        positivos += 1
    elif Numeros[i] < 0:
        negativos += 1
    else:
        ceros += 1

print(f"Positivos: {positivos}")
print(f"Negativos: {negativos}")
print(f"Ceros:     {ceros}")

Positivos: 5
Negativos: 3
Ceros:     1

In [9]:
#Ejercicio numero 9 (hecho por Salvador Romero)
#• Cree una lista con varios números enteros. 
#• Encuentre el número mayor. 
#• Encuentre el número menor. 
#• Calcule la diferencia entre ambos. 
#• Explique el uso de max() y min(). 
numeros = [15, -3, 42, 8, 0, 27, -10, 56, 12, 3]

mayor = max(numeros)
menor = min(numeros)
diferencia = mayor - menor

print(f"Lista: {numeros}")
print(f"Mayor:    {mayor}")
print(f"Menor:    {menor}")
print(f"Diferencia: {diferencia}")

Lista: [15, -3, 42, 8, 0, 27, -10, 56, 12, 3]
Mayor:    56
Menor:    -10
Diferencia: 66

In [10]:
#Ejercicio #10 : Diccionario de Estudiantes (hecho por stephany lopez)
#Enunciado: Crear un diccionario con los datos de un estudiante y mostrar la informacion de forma ordenada
#Logica: Acceder a los valores usando las claves del diccionario.

# Diccionario del estudiante

estudiante = {
    "nombre": "Danny Lopez",
    "edad": 20,
    "carrera": "Ingenieria en Sistemas",
    "promedio": 90,
    "estado": "Aprobado"
}



print("DATOS DEL ESTUDIANTE")
print("--------------------")
print("Nombre:", estudiante["nombre"])
print("Edad:", estudiante["edad"])
print("Carrera:", estudiante["carrera"])
print("Promedio:", estudiante["promedio"])
print("Estado:", estudiante["estado"])

#Explicacion:
#Los valores se acceden usando la clave entre corchetes.
#Ejemplo: estudiante["nombre"]

DATOS DEL ESTUDIANTE
--------------------
Nombre: Danny Lopez
Edad: 20
Carrera: Ingenieria en Sistemas
Promedio: 90
Estado: Aprobado

In [11]:
#Ejercicio #11: Funcion para calcular descuento (hecho por stephany lopez)
#Enunciado: Crear una funcion que calcule el precio
#Logica: Calcular el descuento y mostrar el precio final.

# Función para calcular descuento

def calcular_descuento(precio, descuento):
    precio_final = precio - (precio * descuento / 100)
    return precio_final


precio_original = 1000
porcentaje = 20


resultado = calcular_descuento(precio_original, porcentaje)


print("Precio original:", precio_original)
print("Descuento:", porcentaje, "%")
print("Precio final:", resultado)

# Explicación
#La función recibe el precio original y el porcentaje de descuento.
#La función retorna el precio final con el descuento aplicado.

Precio original: 1000
Descuento: 20 %
Precio final: 800.0

In [12]:

#Ejercicio #12: Validación de contraseña.  (hecho por stephany lopez)
#Enunciado: Crear un programa que valide si una contraseña cumple con los requisitos de seguridad.
#LOgica: El programa revisa si la contraseña cumple los requisitos de seguridad y muestra si es válida o no.

# Contraseña definida

contraseña = "Kere2025"

tiene_numero = any(caracter.isdigit() for caracter in contraseña)
tiene_mayuscula = any(caracter.isupper() for caracter in contraseña)
tiene_minuscula = any(caracter.islower() for caracter in contraseña)
longitud = len(contraseña) >= 8

# Resultado

if tiene_numero and tiene_mayuscula and tiene_minuscula and longitud:
    print("La contraseña es válida")
else:
    print("La contraseña no es válida")

La contraseña es válida

In [13]:
#Ejercicio 13: Sistema simple de inventario
#• Cree una lista de productos.
#• Cada producto debe tener código, nombre, precio y cantidad disponible.
#• Muestre todos los productos.
#• Busque un producto por código.
#• Calcule el valor total del inventario.
    
inventario = [
    {"codigo": "001", "nombre": "bolsa de pan", "precio": 30.0, "cantidad": 10},
    {"codigo": "002", "nombre": "Caja de leche", "precio": 35.0, "cantidad": 5},
    {"codigo": "003", "nombre": "Carton de huevos", "precio": 110.0, "cantidad": 3}
]

print("--- LISTA DE PRODUCTOS ---")
for prod in inventario:
    print(f"Código: {prod['codigo']} | Nombre: {prod['nombre']} | Precio: L{prod['precio']} | Stock: {prod['cantidad']}")

print("-" * 30)

codigo_a_buscar = "002"
encontrado = False

print(f"\n--- BUSCANDO EL CÓDIGO: {codigo_a_buscar} ---")
for prod in inventario:
    if prod["codigo"] == codigo_a_buscar:
        print(f"¡Encontrado! Producto: {prod['nombre']}, Precio: L{prod['precio']}, Stock: {prod['cantidad']}")
        encontrado = True
        break 

if not encontrado:
    print("Producto no encontrado.")

print("-" * 30)

valor_total = 0.0

for prod in inventario:
      valor_total += prod["precio"] * prod["cantidad"]

print(f"\n--- VALOR TOTAL DEL INVENTARIO ---")
print(f"El valor total acumulado es: L{valor_total}")

--- LISTA DE PRODUCTOS ---
Código: 001 | Nombre: bolsa de pan | Precio: L30.0 | Stock: 10
Código: 002 | Nombre: Caja de leche | Precio: L35.0 | Stock: 5
Código: 003 | Nombre: Carton de huevos | Precio: L110.0 | Stock: 3
------------------------------

--- BUSCANDO EL CÓDIGO: 002 ---
¡Encontrado! Producto: Caja de leche, Precio: L35.0, Stock: 5
------------------------------

--- VALOR TOTAL DEL INVENTARIO ---
El valor total acumulado es: L805.0

In [14]:
#Ejercicio 14: Registro de ventas
#• Cree una lista de ventas.
#• Cada venta debe tener cliente, producto, cantidad y precio unitario.
#• Calcule el total por venta.
#• Calcule el total general vendido.
#• Identifique el cliente con la compra más alta.


ventas = [
    {"cliente": "Ana", "producto": "Teclado", "cantidad": 2, "precio_unitario": 15.0},
    {"cliente": "Carlos", "producto": "Monitor", "cantidad": 1, "precio_unitario": 120.0},
    {"cliente": "Juan", "producto": "Mouse", "cantidad": 3, "precio_unitario": 10.0}
]

total_general = 0.0
cliente_mas_alto = ""
compra_mas_alta = 0.0

print("--- DETALLE DE VENTAS ---")

for v in ventas:

    total_venta = v["cantidad"] * v["precio_unitario"]
    print(f"Cliente: {v['cliente']} | Producto: {v['producto']} | Total Venta: L{total_venta}")
    

    total_general += total_venta
    

    if total_venta > compra_mas_alta:
        compra_mas_alta = total_venta
        cliente_mas_alto = v["cliente"]

print("-" * 40)


print(f"Total general vendido en el negocio: L{total_general}")
print(f"El cliente con la compra más alta fue {cliente_mas_alto} (Gastó: L{compra_mas_alta})")

--- DETALLE DE VENTAS ---
Cliente: Ana | Producto: Teclado | Total Venta: L30.0
Cliente: Carlos | Producto: Monitor | Total Venta: L120.0
Cliente: Juan | Producto: Mouse | Total Venta: L30.0
----------------------------------------
Total general vendido en el negocio: L180.0
El cliente con la compra más alta fue Carlos (Gastó: L120.0)

In [15]:
#Ejercicio 15: Limpieza básica de texto
#• Defina o solicite una frase.
#• Elimine espacios al inicio y al final.
#• Convierta el texto a minúsculas.
#• Reemplace espacios dobles por un solo espacio.
#• Cuente cuántas palabras contiene.
#• Explique los métodos strip(), lower(), replace() y split().


frase_mal = "   Hola  Mundo   Clase  Big Data    "

print(f"Frase Original: '{frase_mal}'")

frase_bien = frase_mal.strip()

frase_bien = frase_bien.lower()

frase_bien = frase_bien.replace("  ", " ")
frase_bien = frase_bien.replace("  ", " ")

print(f"Frase Corregida:   '{frase_bien}'")

lista_palabras = frase_bien.split()

total_palabras = len(lista_palabras)

print(f"La frase contiene {total_palabras} palabras.")



#strip():Borra todos los espacios en blanco que estén al inicio y al final del texto. No toca los espacios que están en medio de las palabras.

#lower():Agarra todo el texto y lo convierte por completo a letras minúsculas.

#replace():Intercambia texto. Busca un fragmento de texto y lo cambia por otro. En el ejercicio, buscó "  " (dos espacios juntos) y los transformó en " " (un solo espacio).

#split():Busca los espacios en blanco y los usa para separar las palabras.

Frase Original: '   Hola  Mundo   Clase  Big Data    '
Frase Corregida:   'hola mundo clase big data'
La frase contiene 5 palabras.

In [16]:
#ejercicio 16: dataframe de estudiantes
#enunciado: crear un dataframe con almenos 10 estudiantes, incluir nombre, carrera, edad, promedio y ciudad, mostrar las primeras 5 filas, calcular promedios, mostrar información general del dtf, estudiantes con promedio mayor a 80 y ordenar de mayor a menor
#Lógica: se usa la lógica del ejemplo de los datos de uber de abril 2014 para desarrollar este ejercicio, ya que contiene el head y se usa la lógica del ejemplo 1 del cual se saco el .mean(), lo demas fue razonamiento y un poco de investigación para el manejo de los datos requeridos 


import pandas as pd
from IPython.display import display #este import fue encontrado tras buscar mediante ia cual era la mejor forma para mostrar la información y que fuera más legible.

estudiantes = {
    'nombre':   ['Ana López',    'Carlos Ruiz',  'María Torres', 'Diego Pérez',  'Lucía Gómez',
                 'Andrés Silva', 'Valeria Cruz', 'José Morales', 'Camila Díaz',  'Sebastián Ríos'],
    'carrera':  ['Ingeniería',   'Medicina',     'Derecho',      'Ingeniería',   'Psicología',
                 'Medicina',     'Derecho',      'Ingeniería',   'Psicología',   'Medicina'],
    'edad':     [20, 22, 21, 19, 23, 24, 20, 21, 22, 25],
    'promedio': [85, 92, 78, 65, 88, 95, 73, 82, 90, 60],
    'ciudad':   ['Tegucigalpa', 'San Pedro Sula', 'La Ceiba',    'Choloma',      'El Progreso',
                 'Comayagua',   'Choluteca',      'Tegucigalpa', 'San Pedro Sula', 'La Ceiba']
}

df = pd.DataFrame(estudiantes)


print("Primeras 5 filas:")
display(df.head())

print("Información general:")
df.info()

print(f"\nPromedio general: {df['promedio'].mean():.2f}")

print("\nEstudiantes con promedio >= 80:")
display(df[df['promedio'] >= 80])

print("\nOrdenados por promedio (mayor a menor):")
display(df.sort_values(by='promedio', ascending=False))

Primeras 5 filas:

         nombre     carrera  edad  promedio          ciudad
0     Ana López  Ingeniería    20        85     Tegucigalpa
1   Carlos Ruiz    Medicina    22        92  San Pedro Sula
2  María Torres     Derecho    21        78        La Ceiba
3   Diego Pérez  Ingeniería    19        65         Choloma
4   Lucía Gómez  Psicología    23        88     El Progreso

Información general:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   nombre    10 non-null     str
 1   carrera   10 non-null     str
 2   edad      10 non-null     int64
 3   promedio  10 non-null     int64
 4   ciudad    10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

Promedio general: 80.80

Estudiantes con promedio >= 80:

         nombre     carrera  edad  promedio          ciudad
0     Ana López  Ingeniería    20        85     Tegucigalpa
1   Carlos Ruiz    Medicina    22        92  San Pedro Sula
4   Lucía Gómez  Psicología    23        88     El Progreso
5  Andrés Silva    Medicina    24        95       Comayagua
7  José Morales  Ingeniería    21        82     Tegucigalpa
8   Camila Díaz  Psicología    22        90  San Pedro Sula

Ordenados por promedio (mayor a menor):

           nombre     carrera  edad  promedio          ciudad
5    Andrés Silva    Medicina    24        95       Comayagua
1     Carlos Ruiz    Medicina    22        92  San Pedro Sula
8     Camila Díaz  Psicología    22        90  San Pedro Sula
4     Lucía Gómez  Psicología    23        88     El Progreso
0       Ana López  Ingeniería    20        85     Tegucigalpa
7    José Morales  Ingeniería    21        82     Tegucigalpa
2    María Torres     Derecho    21        78        La Ceiba
6    Valeria Cruz     Derecho    20        73       Choluteca
3     Diego Pérez  Ingeniería    19        65         Choloma
9  Sebastián Ríos    Medicina    25        60        La Ceiba

In [17]:
#ejercicio 17: Anáslis de ventas
#enunciado: Cree un DataFrame de ventas con al menos 15 registros. 
# Incluya fecha, vendedor, producto, categoría, cantidad y precio unitario. 
# Calcule una nueva columna TotalVenta. 
# Calcule el total vendido por vendedor. 
# Identifique el producto más vendido. 
# Identifique la categoría con mayor ingreso. 
# Ordene las ventas de mayor a menor.
#lógica: se usa un acercamiento diferente ya que es basicamente hacer un insert a un df y jugar con los datos que nos da este insert, se usa una lógica tipo prueba de sql para sacar el producto más vendido y la categoría con mayor ingreso, se usa el groupby para agrupar por vendedor y sacar el total vendido por cada uno, luego se ordena el df por la columna TotalVenta de mayor a menor para mostrar las ventas ordenadas.
import pandas as pd
from IPython.display import display


ventas = {
    'fecha':          ['2024-01-05','2024-01-08','2024-01-10','2024-01-12','2024-01-15',
                       '2024-01-17','2024-01-20','2024-01-22','2024-01-25','2024-01-28',
                       '2024-02-01','2024-02-05','2024-02-08','2024-02-12','2024-02-15'],
    'vendedor':       ['Carlos','María','Carlos','Luis','María',
                       'Luis','Carlos','María','Luis','Carlos',
                       'María','Luis','Carlos','María','Luis'],
    'producto':       ['Laptop','Mouse','Teclado','Monitor','Laptop',
                       'Mouse','Monitor','Teclado','Laptop','Mouse',
                       'Monitor','Laptop','Teclado','Mouse','Monitor'],
    'categoria':      ['Computación','Accesorios','Accesorios','Computación','Computación',
                       'Accesorios','Computación','Accesorios','Computación','Accesorios',
                       'Computación','Computación','Accesorios','Accesorios','Computación'],
    'cantidad':       [2, 5, 3, 1, 1, 8, 2, 4, 3, 6, 1, 2, 5, 3, 2],
    'precio_unitario':[850, 25, 45, 320, 850, 25, 320, 45, 850, 25, 320, 850, 45, 25, 320]
}

df = pd.DataFrame(ventas)

df['TotalVenta'] = df['cantidad'] * df['precio_unitario']
prod_mas_vendido = df.groupby('producto')['cantidad'].sum().idxmax() #<- esta sentencia según mi investigación hace que la variable retorne el indice de lo que fue más vendido y no solo me devuelve el valor numérico.
cat_mayor_ingreso = df.groupby('categoria')['TotalVenta'].sum().idxmax()
total_venta = df.groupby('vendedor')['TotalVenta'].sum()
ventas_ordenadas = df.sort_values(by='TotalVenta',ascending=False)

print("total vendido por vendedor: ")
display(total_venta)
print(f"\nProducto más vendido: {prod_mas_vendido}") 
print(f"\nCategoría con mayor ingreso: {cat_mayor_ingreso}")
display(ventas_ordenadas)

total vendido por vendedor:

vendedor
Carlos    2850
Luis      5410
María     1550
Name: TotalVenta, dtype: int64

Producto más vendido: Mouse

Categoría con mayor ingreso: Computación

,fecha,vendedor,producto,categoria,cantidad,precio_unitario,TotalVenta
8,2024-01-25,Luis,Laptop,Computación,3,850,2550
11,2024-02-05,Luis,Laptop,Computación,2,850,1700
0,2024-01-05,Carlos,Laptop,Computación,2,850,1700
4,2024-01-15,María,Laptop,Computación,1,850,850
14,2024-02-15,Luis,Monitor,Computación,2,320,640
6,2024-01-20,Carlos,Monitor,Computación,2,320,640
3,2024-01-12,Luis,Monitor,Computación,1,320,320
10,2024-02-01,María,Monitor,Computación,1,320,320
12,2024-02-08,Carlos,Teclado,Accesorios,5,45,225
5,2024-01-17,Luis,Mouse,Accesorios,8,25,200
7,2024-01-22,María,Teclado,Accesorios,4,45,180
9,2024-01-28,Carlos,Mouse,Accesorios,6,25,150
2,2024-01-10,Carlos,Teclado,Accesorios,3,45,135
1,2024-01-08,María,Mouse,Accesorios,5,25,125
13,2024-02-12,María,Mouse,Accesorios,3,25,75

In [ ]:
#ejercicio 18: limpieza de datos con pandas
#enunciado:
# Ejercicio 18: Limpieza de datos con pandas 
# • Cree un DataFrame con datos incompletos de clientes. 
# • Incluya nombre, edad, correo, ciudad y teléfono. 
# • Identifique valores nulos. 
# • Cuente los valores nulos por columna. 
# • Reemplace ciudades vacías con "No especificada". 
# • Elimine registros que no tengan correo. 
# • Muestre el DataFrame limpio. 
#Lógica: se reviso la documentación de pandas para encontar valores nulos dentro de un df, y con la ayuda de la ia para la sintaxis y comprobación de una lógica correcta se emplearon los metodos encontrados. link de documentación: https://pandas.pydata.org/docs/user_guide/missing_data.html#filling-missing-data. no fue solo la ia que hizo todo, yo me encargue de investigar por mi parte y emplear la lógica para resolver el ejecicio, la ia solo me ayudo con la sintaxis.
import pandas as pd

clientes = {
    'nombre':   ['Ana López',  'Carlos Ruiz', 'Juan Pérez',          'Diego Pérez', 'Lucía Gómez',
                 'Andrés Silva', 'Valeria Torres',         'José Morales', 'Camila Díaz', 'Sebastián Ríos'],
    'edad':     [25,           50,           30,             19,            1,
                 40,           22,             18,           28,            35],
    'correo':   ['ana@gmail.com', 'carlos@gmail.com', None,  'diego@gmail.com', 'lucia@gmail.com',
                 None,          'valeria@gmail.com', 'jose@gmail.com', None, 'sebastian@gmail.com'],
    'ciudad':   ['Tegucigalpa', None,          'La Ceiba',    None,          'San Pedro Sula',
                 'Comayagua',   'Choloma',      None,          'Choluteca',   None],
    'telefono': ['9999-1111',  '8888-2222',    None,          '7777-3333',   None,
                 '6666-4444',   None,           '5555-5555',   None,          '4444-6666']
}

df = pd.DataFrame(clientes)

display(df.isna())

display(df.isna().sum())

df['ciudad'] = df['ciudad'].fillna('No especificada')
df['telefono'] = df['telefono'].fillna('No especificado')
df_limpio = df.dropna(subset=['correo'])
display(df_limpio)

   nombre   edad  correo  ciudad  telefono
0   False  False   False   False     False
1   False  False   False    True     False
2   False  False    True   False      True
3   False  False   False    True     False
4   False  False   False   False      True
5   False  False    True   False     False
6   False  False   False   False      True
7   False  False   False    True     False
8   False  False    True   False      True
9   False  False   False    True     False

nombre      0
edad        0
correo      3
ciudad      4
telefono    4
dtype: int64

           nombre  edad               correo           ciudad         telefono
0       Ana López    25        ana@gmail.com      Tegucigalpa        9999-1111
1     Carlos Ruiz    50     carlos@gmail.com  No especificada        8888-2222
3     Diego Pérez    19      diego@gmail.com  No especificada        7777-3333
4     Lucía Gómez     1      lucia@gmail.com   San Pedro Sula  No especificado
6  Valeria Torres    22    valeria@gmail.com          Choloma  No especificado
7    José Morales    18       jose@gmail.com  No especificada        5555-5555
9  Sebastián Ríos    35  sebastian@gmail.com  No especificada        4444-6666

In [19]:
#ejercico 19: analisis de prestamos
#enunciado: Ejercicio 19: Análisis de préstamos 
# • Cree un DataFrame con solicitudes de préstamo. 
# • Incluya cliente, monto solicitado, plazo, ingreso mensual y estado de solicitud. 
# • Calcule el monto promedio solicitado. 
# • Cuente solicitudes por estado. 
# • Muestre únicamente préstamos aprobados. 
# • Muestre clientes con monto solicitado mayor a 50,000. 
# • Agrupe por estado y calcule el promedio del monto solicitado.

import pandas as pd
from IPython.display import display

prestamos = {
    'cliente':          ['Ana López',    'Carlos Ruiz',  'María Torres', 'Diego Pérez',
                         'Lucía Gómez',  'Andrés Silva', 'Valeria Cruz', 'José Morales',
                         'Camila Díaz',  'Sebastián Ríos', 'Rosa Mejía', 'Pedro Núñez'],
    'monto_solicitado': [25000,  80000,  45000,  120000, 60000,
                         35000,  95000,  15000,  70000,  55000, 40000, 110000],
    'plazo_meses':      [12,     36,     24,     48,     36,
                         12,     60,     24,     36,     48,    24,    60],
    'ingreso_mensual':  [15000,  40000,  22000,  55000,  30000,
                         18000,  58000,  12000,  35000,  280000, 200000, 50000],
    'estado':           ['Aprobado',  'Rechazado', 'Aprobado',  'Aprobado',  'Pendiente',
                         'Rechazado', 'Aprobado',  'Rechazado', 'Pendiente', 'Aprobado',
                         'Pendiente', 'Aprobado']
}

df = pd.DataFrame(prestamos)
monto_promedio = df['monto_solicitado'].mean()
solicitudes_por_estadod = df["estado"].value_counts()
monto_mayor_50k = df[df['monto_solicitado'] > 50000]
prestamos_aprobados = df[df['estado'] == 'Aprobado']
promedio_por_estado = df.groupby('estado')['monto_solicitado'].mean()

print(f"Monto promedio solicitado: L{monto_promedio:.2f}")
print("\nCantidad de solicitudes por estado:")
display(solicitudes_por_estadod)
print("\nPréstamos aprobados:")
display(prestamos_aprobados)
print("\nClientes con monto solicitado mayor a 50,000:")
display(monto_mayor_50k)
print("\nPromedio del monto solicitado por estado:")
display(promedio_por_estado)

Monto promedio solicitado: L62500.00

Cantidad de solicitudes por estado:

estado
Aprobado     6
Rechazado    3
Pendiente    3
Name: count, dtype: int64

Préstamos aprobados:

           cliente  monto_solicitado  plazo_meses  ingreso_mensual    estado
0        Ana López             25000           12            15000  Aprobado
2     María Torres             45000           24            22000  Aprobado
3      Diego Pérez            120000           48            55000  Aprobado
6     Valeria Cruz             95000           60            58000  Aprobado
9   Sebastián Ríos             55000           48           280000  Aprobado
11     Pedro Núñez            110000           60            50000  Aprobado

Clientes con monto solicitado mayor a 50,000:

           cliente  monto_solicitado  plazo_meses  ingreso_mensual     estado
1      Carlos Ruiz             80000           36            40000  Rechazado
3      Diego Pérez            120000           48            55000   Aprobado
4      Lucía Gómez             60000           36            30000  Pendiente
6     Valeria Cruz             95000           60            58000   Aprobado
8      Camila Díaz             70000           36            35000  Pendiente
9   Sebastián Ríos             55000           48           280000   Aprobado
11     Pedro Núñez            110000           60            50000   Aprobado

Promedio del monto solicitado por estado:

estado
Aprobado     75000.000000
Pendiente    56666.666667
Rechazado    43333.333333
Name: monto_solicitado, dtype: float64

In [20]:
#ejercicio 20_  Mini analisis de datos tipo empresa
#enunciado: Cree un DataFrame con información de empleados. 
# • Incluya nombre, departamento, cargo, salario, años de experiencia y ciudad. 
# • Muestre los primeros registros. 
# • Muestre estadísticas generales de salarios. 
# • Calcule el salario promedio por departamento. 
# • Encuentre el empleado con salario más alto. 
# • Muestre empleados con más de 5 años de experiencia. 
# • Ordene empleados por salario. 
# • Cree una columna NivelExperiencia: Junior, Intermedio o Senior.

import pandas as pd
from IPython.display import display

empleados = {
    'nombre':       ['Ana López',    'Carlos Ruiz',  'María Torres', 'Diego Pérez',
                     'Lucía Gómez',  'Andrés Silva', 'Valeria Cruz', 'José Morales',
                     'Camila Díaz',  'Sebastián Ríos','Rosa Mejía',  'Pedro Núñez',
                     'Laura Reyes',  'Mario Castro', 'Sofia Mendez'],
    'departamento': ['TI',        'Ventas',    'RRHH',     'TI',       'Finanzas',
                     'Ventas',    'TI',        'RRHH',     'Finanzas', 'TI',
                     'Ventas',    'Finanzas',  'RRHH',     'TI',       'Ventas'],
    'cargo':        ['Desarrollador', 'Ejecutivo',   'Analista',    'Arquitecto',  'Contador',
                     'Supervisor',    'Desarrollador','Coordinador', 'Analista',    'DBA',
                     'Ejecutivo',     'Gerente',      'Analista',    'Desarrollador','Supervisor'],
    'salario':      [35000, 28000, 22000, 65000, 40000,
                     32000, 38000, 25000, 42000, 50000,
                     30000, 70000, 24000, 36000, 33000],
    'anios_exp':    [3,  6,  2,  10, 7,
                     5,  4,  3,  8,  9,
                     2,  12, 1,  4,  6],
    'ciudad':       ['Tegucigalpa', 'San Pedro Sula', 'La Ceiba',     'Tegucigalpa', 'Comayagua',
                     'Choloma',     'Tegucigalpa',    'San Pedro Sula','La Ceiba',   'Tegucigalpa',
                     'Comayagua',   'Tegucigalpa',    'Choloma',       'La Ceiba',   'San Pedro Sula']
}

df = pd.DataFrame(empleados)

salario_promedio = df.groupby('departamento')['salario'].mean().round(2)
hola = df.loc[df['salario'].idxmax()] #<- lo que esto hace es que primero, se hace la busqueda del salario mas alto y con el idxmax solo devuelvo el indice en el que esta este valor, despues con el loc le digo al código "dame la fila completa que tiene el indice correspondiente" y por eso cuando se hace el display(hola) se muestra toda la información del empleado con el salario más alto y no solo el salario. 
#el loc permite hacer más busquedas dentro del df, por ejemplo, si quisiera saber el salario del empleado con el salario más alto, podría hacer hola['salario'] y me devolvería solo el salario de ese empleado, pero como se hizo el display(hola) se muestra toda la fila con toda la información de ese empleado.

print("Primeros registros:")
display(df.head())
print("\nEstadísticas generales de salarios:")
display(df['salario'].describe().round(2))
print("\nSalario promedio por departamento:")
display(salario_promedio)
print('\n Empleado con el salario más alto:')
display(hola)
print('\n Empleados con más de 5 años de experiencia:')
display(df[df['anios_exp'] > 5])
print('\n Empleados ordenados por salario (de mayor a menor):')
display(df.sort_values(by='salario',ascending=False))
#lo hago al final ya que es el ultimo paso que se pide para terminar el ejercicio
def nivel_exp(anios):
    if anios <= 3:
        return 'Junior'
    elif anios <= 6:
        return 'Intermedio'
    else:
        return 'Senior'
anios_exp = df['NivelExperiencia'] = df['anios_exp'].apply(nivel_exp)
display(df)

Primeros registros:

,nombre,departamento,cargo,salario,anios_exp,ciudad
0,Ana López,TI,Desarrollador,35000,3,Tegucigalpa
1,Carlos Ruiz,Ventas,Ejecutivo,28000,6,San Pedro Sula
2,María Torres,RRHH,Analista,22000,2,La Ceiba
3,Diego Pérez,TI,Arquitecto,65000,10,Tegucigalpa
4,Lucía Gómez,Finanzas,Contador,40000,7,Comayagua

Estadísticas generales de salarios:

count       15.0
mean     38000.0
std      14081.4
min      22000.0
25%      29000.0
50%      35000.0
75%      41000.0
max      70000.0
Name: salario, dtype: float64

Salario promedio por departamento:

departamento
Finanzas    50666.67
RRHH        23666.67
TI          44800.00
Ventas      30750.00
Name: salario, dtype: float64

 Empleado con el salario más alto:

nombre          Pedro Núñez
departamento       Finanzas
cargo               Gerente
salario               70000
anios_exp                12
ciudad          Tegucigalpa
Name: 11, dtype: object

 Empleados con más de 5 años de experiencia:

,nombre,departamento,cargo,salario,anios_exp,ciudad
1,Carlos Ruiz,Ventas,Ejecutivo,28000,6,San Pedro Sula
3,Diego Pérez,TI,Arquitecto,65000,10,Tegucigalpa
4,Lucía Gómez,Finanzas,Contador,40000,7,Comayagua
8,Camila Díaz,Finanzas,Analista,42000,8,La Ceiba
9,Sebastián Ríos,TI,DBA,50000,9,Tegucigalpa
11,Pedro Núñez,Finanzas,Gerente,70000,12,Tegucigalpa
14,Sofia Mendez,Ventas,Supervisor,33000,6,San Pedro Sula

 Empleados ordenados por salario (de mayor a menor):

,nombre,departamento,cargo,salario,anios_exp,ciudad
11,Pedro Núñez,Finanzas,Gerente,70000,12,Tegucigalpa
3,Diego Pérez,TI,Arquitecto,65000,10,Tegucigalpa
9,Sebastián Ríos,TI,DBA,50000,9,Tegucigalpa
8,Camila Díaz,Finanzas,Analista,42000,8,La Ceiba
4,Lucía Gómez,Finanzas,Contador,40000,7,Comayagua
6,Valeria Cruz,TI,Desarrollador,38000,4,Tegucigalpa
13,Mario Castro,TI,Desarrollador,36000,4,La Ceiba
0,Ana López,TI,Desarrollador,35000,3,Tegucigalpa
14,Sofia Mendez,Ventas,Supervisor,33000,6,San Pedro Sula
5,Andrés Silva,Ventas,Supervisor,32000,5,Choloma
10,Rosa Mejía,Ventas,Ejecutivo,30000,2,Comayagua
1,Carlos Ruiz,Ventas,Ejecutivo,28000,6,San Pedro Sula
7,José Morales,RRHH,Coordinador,25000,3,San Pedro Sula
12,Laura Reyes,RRHH,Analista,24000,1,Choloma
2,María Torres,RRHH,Analista,22000,2,La Ceiba

,nombre,departamento,cargo,salario,anios_exp,ciudad,NivelExperiencia
0,Ana López,TI,Desarrollador,35000,3,Tegucigalpa,Junior
1,Carlos Ruiz,Ventas,Ejecutivo,28000,6,San Pedro Sula,Intermedio
2,María Torres,RRHH,Analista,22000,2,La Ceiba,Junior
3,Diego Pérez,TI,Arquitecto,65000,10,Tegucigalpa,Senior
4,Lucía Gómez,Finanzas,Contador,40000,7,Comayagua,Senior
5,Andrés Silva,Ventas,Supervisor,32000,5,Choloma,Intermedio
6,Valeria Cruz,TI,Desarrollador,38000,4,Tegucigalpa,Intermedio
7,José Morales,RRHH,Coordinador,25000,3,San Pedro Sula,Junior
8,Camila Díaz,Finanzas,Analista,42000,8,La Ceiba,Senior
9,Sebastián Ríos,TI,DBA,50000,9,Tegucigalpa,Senior
10,Rosa Mejía,Ventas,Ejecutivo,30000,2,Comayagua,Junior
11,Pedro Núñez,Finanzas,Gerente,70000,12,Tegucigalpa,Senior
12,Laura Reyes,RRHH,Analista,24000,1,Choloma,Junior
13,Mario Castro,TI,Desarrollador,36000,4,La Ceiba,Intermedio
14,Sofia Mendez,Ventas,Supervisor,33000,6,San Pedro Sula,Intermedio